### ISSUE TITLE
default sound-theme

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/deepin-artwork-themes#1]
**theme.ini** is set to

```
SoundTheme=deepin
```

At the same time in **deepin-desktop-schemas** I find this gsetting:

```
[com.deepin.wrap.gnome.desktop.sound]
theme-name='LinuxDeepin'
event-sounds=true
```

Is this difference intentional? Or is one of them wrong?

**Comment by fasheng** [comment]
well, the sound theme in theme.ini is designed for theme tarballs, and still not used now.......

for the default sound theme name, it is 'deepin', and all other 'LinuxDeepin' keywords will be renamed later, too.

2015年12月2日 下午8:15, 下午8:15，在 Bernhard Landauer notifications@github.com 已写:

**Comment by oberon-manjaro** [comment]
thanks for the clarification :)
